#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
use minapp\system\BuildDatabase;


$application = new Application();
$application->add(new BuildDatabase());
$application->run();